#!/bin/sh
# Reproducible validation for milestone 1 (repaired implementation).
# Run from the repository root. Every reported numerical table in REPORT.md
# is generated by one of the commands below; no table requires guessing.
set -eu
cd "$(dirname "$0")/.."

echo "--- maintained test suite ---"
PYTHONPATH=src ./.venv/bin/python -m pytest tests/ -q

echo "--- documented single-case examples ---"
PYTHONPATH=src ./.venv/bin/python -m espresso_m1.cli run \
  --config configs/default.json --out-dir outputs/case
PYTHONPATH=src ./.venv/bin/python -m espresso_m1.cli run \
  --config configs/uniform.json --out-dir outputs/case_uniform_9bar

echo "--- documented pressure sweeps ---"PYTHONPATH=src ./.venv/bin/python -m espresso_m1.cli sweep \
  --config configs/uniform.json --p-in-bar "1:12:1" \
  --out outputs/sweep_uniform_full.csv
PYTHONPATH=src ./.venv/bin/python -m espresso_m1.cli sweep \
  --config configs/default.json --p-in-bar "1:12:1" \
  --out outputs/sweep_compaction_full.csv
PYTHONPATH=src ./.venv/bin/python -m espresso_m1.cli sweep \
  --config configs/default.json --set R_perf=0.0145 --p-in-bar "1:12:1" \
  --out outputs/sweep_compaction_perf.csv

echo "--- documented transport examples (milestone 2) ---"
PYTHONPATH=src ./.venv/bin/python -m espresso_m1.cli transport \
  --config configs/default.json --tconfig configs/transport_extraction.json \
  --set R_perf=0.0145 --out-dir outputs/transport_extraction
PYTHONPATH=src ./.venv/bin/python -m espresso_m1.cli transport \
  --config configs/uniform.json --tconfig configs/transport_tracer.json \
  --out-dir outputs/transport_tracer

echo "--- independent review probe (supplemental evidence) ---"
PYTHONPATH=src ./.venv/bin/python review/probe_submission.py --wheel \
  --out review/repaired_results.json
